apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  #replica set labels
  labels:
    purpose: replicaset-demo
    project: roboshop
    app: nginx
spec:
  replicas: 3
  # labels to create a replicaset
  selector:
    matchLabels:
      purpose: replicaset-demo
      project: roboshop
      app: nginx
  #pod definition
  template:
    metadata:
      labels:
        purpose: replicaset-demo
        project: roboshop
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx