apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  #deployment labels
  labels:
    purpose: deployment-demo
    project: roboshop
    app: nginx
spec:
  replicas: 3
  # labels to create a deployment
  selector:
    matchLabels:
      purpose: deployment-demo
      project: roboshop
      app: nginx
  #pod definition
  template:
    metadata:
      labels:
        purpose: deployment-demo
        project: roboshop
        app: nginx
    spec:
      containers:
      - name: nginx
        #image: nginx
        image: nginx:stable-perl